### ISSUE TITLE
Failed to resolve data length for PascalString255

### ISSUE THREAD

**Issue by kabiri** [huettenhain/dhrake#10]
Hello
when i run it , show error

`Failed to resolve data length for PascalString255
ghidra.program.model.util.CodeUnitInsertionException: Failed to resolve data length for PascalString255
	at ghidra.program.database.code.CodeManager.createCodeUnit(CodeManager.java:2018)
	at ghidra.program.database.ListingDB.createData(ListingDB.java:284)
	at ghidra.program.flatapi.FlatProgramAPI.createData(FlatProgramAPI.java:1717)
	at DhrakeParseClass.run(DhrakeParseClass.java:46)
	at ghidra.app.script.GhidraScript.executeNormal(GhidraScript.java:403)
	at ghidra.app.script.GhidraScript.doExecute(GhidraScript.java:258)
	at ghidra.app.script.GhidraScript.execute(GhidraScript.java:236)
	at ghidra.app.plugin.core.script.RunScriptTask.run(RunScriptTask.java:47)
	at ghidra.util.task.Task.monitoredRun(Task.java:134)
	at ghidra.util.task.TaskRunner.lambda$startTaskThread$0(TaskRunner.java:106)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)

---------------------------------------------------
Build Date: 2024-Apr-10 1518 EDT
Ghidra Version: 11.0.3
Java Home: C:\Program Files\Eclipse Adoptium\jdk-17.0.9.9-hotspot
JVM Version: Eclipse Adoptium 17.0.9
OS: Windows 10 10.0 amd64
Workstation: ZIGSOFTWARE
`

**Comment by huettenhain** [comment]
For me to help you, you will need to provide exact steps to reproduce this, not just an error trace 😉. So, preferably, the sample you were analysing and what exactly you did at what offset in the code.

**Comment by kabiri** [comment]
I followed the steps in the description.
I don't see any phrase starting with VMT_ anywhere in the code.
I find and select code like this `local_2c._0_4_ = 0x9bf45f;` in the decompiled section and run the script.

**Comment by sarog** [comment]
Hi @kabiri, you can find `VMT_` labels using the Symbol Tree window in Ghidra. Take a look [here](https://github.com/huettenhain/dhrake/issues/2#issuecomment-1604898223) for more information on how to use Dhrake (and read through the [entire thread](https://github.com/huettenhain/dhrake/issues/2) too for more tips!). If you aren't seeing any `VMT_` labels, then something went wrong with the IDC generation or a step was omitted.

**Comment by fredurble** [comment]
Hello, I also had the same issue with the error message "`Failed to resolve data length for PascalString255" when trying to run the DHRAKEPARSECLASS . I did analyze the EXE, then ran the DHRAKEINIT script and selected the IDC file that was output from your version of IDR. I also do not have any VMT_ labels after running the DHRAKEINIT script.

**Comment by huettenhain** [comment]
I will close this out, assuming that @sarog's comment resolved the issue. I am not even sure why this stayed open for so long.
